version: "3"

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  server:
    build: .
    env_file: .env
    ports:
      - "80:80"
    environment:
      - HTTP_PORT=80
      - REDIS_URL=redis://cache