version: "3"

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./redis-data:/data
    expose:
      - 6379
    entrypoint: redis-server --appendonly yes
    restart: always

  server:
    build: .
    env_file: .env
    ports:
      - "80:80"
    environment:
      - HTTP_PORT=80
      - REDIS_HOST=redis
    restart: always
